### PR TITLE
feat: refactor api of dcdcr

### PR DESCRIPTION
**Pull request by ramnathv**
@richierocks As promised, here is a PR for the refactor. The best way to test this out is to pull and switch over to this branch and build the package.

1. Add a ` .Rprofile` to the package folder that contains all the AWS parameters as environment variables.
2. Run the code in `README.Rmd`.

### CODE REVIEW

**Comment by richierocks** [comment]
I made few tweaks to your code.

- `paws::s3()` wasn't picking up the environment variables, so I reinstated `create_s3_session()` but as an internal function used by `list_objects_s3()` and `s3_tbl()`.
- I changed the names of the environment variables back to match those described in the [Support article](https://support.datacamp.com/hc/en-us/articles/4409359070871-Storing-Amazon-S3-credentials).
- I added a `tryCatch()` block to `s3_tbl()` which will hopeful avert problems if the DAG fails and some files aren't written to S3.
- I made `s3_help()` safe for cases where there aren't any docs yet (`date_dim` and the track tables).
- I got rid of the `eval(parse())` code borrowing the [function factory pattern from Advanced R](https://adv-r.hadley.nz/function-factories.html).

**Comment by richierocks** [comment]
Some stuff that still needs thinking about:

- For converting the raw content returned from `s3$get_object()$Body` to a CSV I [previously used ](https://github.com/datacamp/dcdcr/blob/master/R/internal.R#L21-L22)`rawToChar()` then called `fread()` on the resulting character. I notice you changed it to write to a file the read it back in. Is that needed for memoization? Otherwise my guess is that it would be slower.
- Because we are no longer exposing `create_s3_session()`, users have to store the credentials as environment variables; they can't pass them directly into `data_connector()`. Are we OK with that or should we give them flexibility?

**Comment by ramnathv** [comment]
> I made few tweaks to your code.

Thanks for the tweaks.

> * `paws::s3()` wasn't picking up the environment variables, so I reinstated `create_s3_session()` but as an internal function used by `list_objects_s3()` and `s3_tbl()`.

> * I changed the names of the environment variables back to match those described in the [Support article](https://support.datacamp.com/hc/en-us/articles/4409359070871-Storing-Amazon-S3-credentials).

It is unfortunate that the support article does not use the default environment variables that was packages have come to expect. If we can standardize on this, we no longer have to keep passing anything to the functions since they will be picked up automatically. The standard env variable is shown below. If we standardize, R and Python libraries will work out of the box and we can avoid further mangling. Can we update the support article?

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_BUCKET
AWS_REGION
AWS_ATHENA_S3_STAGING_DIR
```


> * I added a `tryCatch()` block to `s3_tbl()` which will hopeful avert problems if the DAG fails and some files aren't written to S3.

Good point. One suggestion is to use `purrr::safely` to define a safe version of the function.

> * I made `s3_help()` safe for cases where there aren't any docs yet (`date_dim` and the track tables).

Awesome! Thanks.

> * I got rid of the `eval(parse())` code borrowing the [function factory pattern from Advanced R](https://adv-r.hadley.nz/function-factories.html).

Great! I used `eval(parse)` originally to expose the underlying function call. But it is not important and safety is key.

**Comment by ramnathv** [comment]
> Some stuff that still needs thinking about:
> 
> * For converting the raw content returned from `s3$get_object()$Body` to a CSV I [previously used ](https://github.com/datacamp/dcdcr/blob/master/R/internal.R#L21-L22)`rawToChar()` then called `fread()` on the resulting character. I notice you changed it to write to a file the read it back in. Is that needed for memoization? Otherwise my guess is that it would be slower.

I wrote it to file since I was using `read_csv` and it does NOT support reading text. We can skip the write-to-file step. I think caching will work even without that since it is cached to memory and not filesystem. We might want to think about memory vs. filesystem for later.

> * Because we are no longer exposing `create_s3_session()`, users have to store the credentials as environment variables; they can't pass them directly into `data_connector()`. Are we OK with that or should we give them flexibility?

I think giving people the flexibility makes them more likely to pass them as parameters directly. They can also do `Sys.setenv`, but at least they are consciously aware. Ideally, Enterprise should set the env variables automatically for customers so they don't have to do any fiddling.

**Comment by ramnathv** [comment]
@richierocks Thanks for a thorough review and for making much-needed changes to the code. I am working through some more tweaks and will push them tonight with comments so we can finalize this PR and merge.

---

 I realized that by sticking a small bit of code in `.onLoad`, we can work through the different versions of environment variable names. Doing this will allow us to use `paws::s3()` directly and any other service (e.g. Athena) without having to configure each one separately. 
 
 I am also adding a `check_credentials` function that checks if all the required environment variables are correctly defined and if NOT point them to a support article. Ideally, we should have instructions for both workspace use and non-workspace use. Currently, I just stick them in a `.Rprofile` at the root of my project folder so it is automatically picked up.

```r
  # Set default environment variables expected by paws::s3()
  if (Sys.getenv('AWS_BUCKET') == ''){
    Sys.setenv('AWS_BUCKET' = Sys.getenv('AWS_S3_BUCKET_NAME'))
  }
  if (Sys.getenv('AWS_REGION') == ''){
    Sys.setenv('AWS_REGION' = Sys.getenv('AWS_DEFAULT_REGION'))
  }
  ```

**Comment by richierocks** [comment]
The environment variable names came from the [aws.s3](https://github.com/cloudyr/aws.s3) package - I only switched to paws later. So yeah, they probably ought to be changed. We'll have to give Brian a heads up about this breaking change.

**Comment by richierocks** [comment]
Maybe use functions like this?

```r
get_aws_bucket_env_var <- function() {
  Sys.getenv("AWS_BUCKET", Sys.getenv("AWS_S3_BUCKET_NAME"))
}
get_aws_region_env_var <- function() {
  Sys.getenv("AWS_REGION", Sys.getenv("AWS_DEFAULT_REGION"))
}
```

**Review by richierocks — APPROVED** [review]
looking good

**Pull request merged**
